# Site settings
title: TermSuite
email: "[firstname.lastname]@univ-nantes.fr"
description: TermSuite is a Java UIMA-based toolbox for  efficient <strong>terminology extraction</strong> and <strong>multilingual term alignment</strong>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://termsuite.univ-nantes.fr" # the base hostname & protocol for your site
github_username:  termsuite
github: https://github.com/termsuite/termsuite-core

termsuite:
  maven: http://search.maven.org/remotecontent?filepath=fr/univ-nantes/termsuite/termsuite-core/
  version: "2.0"

resources:
  jar: https://logiciels.lina.univ-nantes.fr/redmine/attachments/download/555/termsuite-resources.jar
  filename: termsuite-resources.jar

corpus:
  we: http://www.lina.univ-nantes.fr/taln/maven/wind-energy.tgz
  mobile: http://www.lina.univ-nantes.fr/taln/maven/mobile-technology.tar.gz

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  parse_block_html: true

collections:
  documentation:
    output: true
    permalink: /documentation/:path/
